[package]
name = "neptunectl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "neptunectl"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
fastrand = "2.1.1"
ripunzip = "2.0.0"

[dev-dependencies]
tempfile = "3.13.0"
